server:
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      suffix: .log
      pattern: '%h %l %u %t "%r" %s %b %D'

overpass:
  urls:
    - https://overpass-api.de/api/interpreter
    - https://lz4.overpass-api.de/api/interpreter
    - https://overpass.kumi.systems/api/interpreter
    - https://overpass.osm.ch/api/interpreter

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/poi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:poi_user}
    password: ${DATABASE_PASSWORD:your_password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
logging:
  level:
    root: INFO
    com.location.poi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
  file:
    name: logs/poi-backend.log
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%X{requestId}]){yellow} %clr(%logger{36}){cyan} %clr(:){faint} %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{requestId}] %logger{36} - %msg%n"
